FORMAT: 1A
HOST: https://api.trainerize.com/

# Trainerize Public API

This is the documentation for the Trainerize Public API

## Group Body Stats 

## Add Body Stats for Client [/bodystats/add]
### /bodystats/add [POST]

Add a client's body stats

---

#### Request Fields:

| Name | Type | Required | Description |
|------|--|-| --------- |
| userID | long | Yes | ID of the client to be queried
| date | date | Yes | ```YYYY-MM-DD``` |
| status | string | Yes | ```scheduled``` |
| unitWeight | string | No | ```kg```, ```lbs``` |
| unitBodystats | string | No | ```inches```, ```cm``` |

#### Response Fields
| Name | Type | Description |
|------|--|---------|
| bodyStatsid | long | dailybodystatus id |

---

#### Errors
| HTTP status | statusMsg | Comments |
| - | --- | --------- |
| 403 | Foribdden access | Client can only access own data |
| 404 | Not found | User not found |
| 406 | Not acceptable | User can only have one bodystats a day |
| 500 | Internal server error | General server error |


+ Request (application/json)

        {
            "userID": {{clientID}},
            "date" : "2018-06-27",
            "status" : "scheduled",
            "unitWeight": "lbs", 
            "unitBodystats":"inches"
        }

+ Response 200 (application/json)

        {
            "bodyStatsID": 943113
        }



## Delete Client Body States [/bodystats/delete]
### /bodystats/delete [POST]

---

#### Request Fields
| Name | Type | Description |
| --- | -- | --------- |
| userID | long | the user ID to delete the body stats for |
| date | date | ```YYYY-MM-DD```  |

---

#### Success
| HTTP status | code | statusMsg | Comments |
| - | - | --- | --------- |
| 200 | 0 | OK | Successful |
| 200 | 3 | OK | Bodystat id not found or bodystat not found on that date |

#### Errors
| HTTP status | statusMsg | Comments |
| - | --- | --------- | 
| 500 | Internal server error | General server error |

+ Request (application/json)

        {
            "userID": {{clientID}},
            "date":"2018-06-27"
        }


+ Response 200 (application/json)

        {
            "msg": "Succesfull",
            "status": 0
        }


## Set Client Body Stats [/questions/2]
### /bodystats/set [POST]
Set the body stats of a client.

---

#### Request Fields:

| Name | Type | Required | Description |
|------|--|-| --------- |
| userid | long | Yes | ID of the client to be queried
| date | string | Yes | ```YYYY-MM-DD``` |
| unitWeight | string | No | ```kg```, ```lbs``` |
| unitBodystats | string | No | ```cm```, ```inches``` |
| bodyMeasures | object | Yes | see object fields below |

###### bodyMeasures
| Name | Type |
| ------ | --- |
| date | date |
| bodyWeight | decimal |
| bodyFatPercent | decimal |
| leanBodyMass | decimal |
| fatMass | decimal |
| chest | decimal |
| shoulders | decimal |
| rightBicep | decimal |
| leftBicep | decimal |
| rightForearm | decimal |
| leftForearm | decimal |
| rightThigh | decimal |
| leftThigh | decimal |
| rightCalf | decimal |
| leftCalf | decimal |
| waist | decimal |
| hips | decimal |
| neck | decimal |
| bloodPressureDiastolic | int |
| bloodPressureSystolic | int |
| caliperBF | decimal |
| caliperMode | byte |
| caliperChest | decimal |
| caliperTriceps | decimal |
| caliperSubscapular | decimal |
| caliperAxilla | decimal |
| caliperAbdomen | decimal |

---

#### Success
| HTTP status | code | statusMsg | Comments |
| - | - | --- | --------- |
| 200 | 0 | OK | Successful. { "bodyMeasures": null, "code": 0} |

#### Errors 
| HTTP status | code | statusMsg | Comments |
| - | - | --- | --------- |
| 404 | | Not found | User not found |
| 406 | 10 | Not acceptable | User can only have one bodystats a day |
| 412 | | Precondition failed | Missing date field |
| 500 | | Internal server error | General server error |

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }



## Get Client Body Stat [/questions/{question_id}]
### /bodystats/get [GET]

Get the body stats of a client.

---

#### Request Fields:

| Name | Type | Required | Description |
|------|--|-| --------- |
| userID | long | Yes | ID of the client to be queried
| date | string | Yes | ```YYYY-MM-DD``` (no timezone); will grab the most recent body stat entry  |
| unitWeight | string | Yes | ```kg```, ```lbs``` |
| unitBodystats | string | Yes | ```inches```, ```cm``` |
| unitDistance | string | No | ```miles```, ```km```|

#### Response Fields:
| Name | Type | Description |
|------|--| --------- |
| id | long | body status ID |
| status | string | ```scheduled```, ```tracked``` |
| bodyMeasures | object | see object fields below |
| from | string | ```trainerize```, ```fitbit```, ```withings``` |
| fromProgram | boolean ||

###### bodyMeasures
| Name | Type |
| ------ | --- |
| date | date |
| bodyWeight | decimal |
| bodyFatPercent | decimal |
| leanBodyMass | decimal |
| fatMass | decimal |
| chest | decimal |
| shoulders | decimal |
| rightBicep | decimal |
| leftBicep | decimal |
| rightForearm | decimal |
| leftForearm | decimal |
| rightThigh | decimal |
| leftThigh | decimal |
| rightCalf | decimal |
| leftCalf | decimal |
| waist | decimal |
| hips | decimal |
| neck | decimal |
| bloodPressureDiastolic | int |
| bloodPressureSystolic | int |
| caliperBF | decimal |
| caliperMode | byte |
| caliperChest | decimal |
| caliperTriceps | decimal |
| caliperSubscapular | decimal |
| caliperAxilla | decimal |
| caliperAbdomen | decimal |

---

#### Errors
| HTTP status | statusMsg | Comments |
| - | --- | --------- |
| 406 | Not acceptable | Missing date field | 
| 406 | Not acceptable | | Unit weight missing |
| 406 | Not acceptable | | Unit bodystats missing |
| 404 | Not found | User not found |
| 404 | Not found | Can't find the bodystats |
| 412 | Precondition failed | No entry on the date |
| 500 | Internal server error | General server error |

+ Parameters
    + question_id (number) - ID of the client to be queried

+ Response 200 (application/json)

            {
                "question": "Favourite programming language?",
                "published_at": "2014-11-11T08:40:51.620Z",
                "url": "/questions/1",
                "choices": [
                    {
                        "choice": "Swift",
                        "url": "/questions/1/choices/1",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "url": "/questions/1/choices/2",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "url": "/questions/1/choices/3",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "url": "/questions/1/choices/4",
                        "votes": 256
                    }
                ]
            }